"""empty message

Revision ID: 5ff17c593681
Revises: 
Create Date: 2019-12-21 10:12:47.594387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff17c593681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_user_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('did_attend', sa.Boolean(), nullable=True),
    sa.Column('did_rsvp', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('event_host', sa.String(), nullable=True),
    sa.Column('rsvp_date', sa.DateTime(), nullable=True),
    sa.Column('date_joined_group', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendance')
    op.drop_table('events')
    # ### end Alembic commands ###
