"""empty message

Revision ID: 9d099bc07232
Revises: 6a7d58251077
Create Date: 2019-05-18 10:49:52.731101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d099bc07232'
down_revision = '6a7d58251077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_user_id', sa.String(), nullable=True),
    sa.Column('meeting_id', sa.String(), nullable=True),
    sa.Column('did_attend', sa.Boolean(), nullable=True),
    sa.Column('did_rsvp', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('event_host', sa.String(), nullable=True),
    sa.Column('rsvp_date', sa.DateTime(), nullable=True),
    sa.Column('date_joined_group', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendance')
    # ### end Alembic commands ###
