"""empty message

Revision ID: a732239357b7
Revises: 9d099bc07232
Create Date: 2019-05-18 10:51:29.016721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a732239357b7'
down_revision = '9d099bc07232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendance', sa.Column('event_id', sa.String(), nullable=True))
    op.drop_column('event_attendance', 'meeting_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendance', sa.Column('meeting_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_attendance', 'event_id')
    # ### end Alembic commands ###
